# Site Settings
title: "Minqi Geng's Homepage"
description: "Personal homepage of Minqi Geng, a Cryptography researcher."
url: "https://goingon17.github.io"
baseurl: ""

# Build Settings
remote_theme: jekyll/minima # Just as a fallback, but we use our own index.html
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Dockerfile
  - docker-compose.yaml
  - package.json
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - talkmap.py
  - talkmap.ipynb
  - talkmap_out.ipynb
  - scripts/
